"""Every country the store can ship to — ISO 3166-1 code, Arabic name, English name.

Used by migration 0004 (first load) and `manage.py seed_store`. Arabic/English names come
from Unicode CLDR. Everything here is only the starting data: the countries, their names,
shipping prices and on/off switch are all managed from the dashboard («الدول والشحن»).
"""

COUNTRIES = [
    ('AF', 'أفغانستان', 'Afghanistan'),
    ('AL', 'ألبانيا', 'Albania'),
    ('DZ', 'الجزائر', 'Algeria'),
    ('AS', 'ساموا الأمريكية', 'American Samoa'),
    ('AD', 'أندورا', 'Andorra'),
    ('AO', 'أنغولا', 'Angola'),
    ('AI', 'أنغويلا', 'Anguilla'),
    ('AG', 'أنتيغوا وبربودا', 'Antigua & Barbuda'),
    ('AR', 'الأرجنتين', 'Argentina'),
    ('AM', 'أرمينيا', 'Armenia'),
    ('AW', 'أروبا', 'Aruba'),
    ('AU', 'أستراليا', 'Australia'),
    ('AT', 'النمسا', 'Austria'),
    ('AZ', 'أذربيجان', 'Azerbaijan'),
    ('BS', 'جزر البهاما', 'Bahamas'),
    ('BH', 'البحرين', 'Bahrain'),
    ('BD', 'بنغلاديش', 'Bangladesh'),
    ('BB', 'بربادوس', 'Barbados'),
    ('BY', 'بيلاروس', 'Belarus'),
    ('BE', 'بلجيكا', 'Belgium'),
    ('BZ', 'بليز', 'Belize'),
    ('BJ', 'بنين', 'Benin'),
    ('BM', 'برمودا', 'Bermuda'),
    ('BT', 'بوتان', 'Bhutan'),
    ('BO', 'بوليفيا', 'Bolivia'),
    ('BA', 'البوسنة والهرسك', 'Bosnia & Herzegovina'),
    ('BW', 'بوتسوانا', 'Botswana'),
    ('BR', 'البرازيل', 'Brazil'),
    ('VG', 'جزر فيرجن البريطانية', 'British Virgin Islands'),
    ('BN', 'بروناي', 'Brunei'),
    ('BG', 'بلغاريا', 'Bulgaria'),
    ('BF', 'بوركينا فاسو', 'Burkina Faso'),
    ('BI', 'بوروندي', 'Burundi'),
    ('KH', 'كمبوديا', 'Cambodia'),
    ('CM', 'الكاميرون', 'Cameroon'),
    ('CA', 'كندا', 'Canada'),
    ('CV', 'الرأس الأخضر', 'Cape Verde'),
    ('BQ', 'هولندا الكاريبية', 'Caribbean Netherlands'),
    ('KY', 'جزر كايمان', 'Cayman Islands'),
    ('CF', 'جمهورية أفريقيا الوسطى', 'Central African Republic'),
    ('TD', 'تشاد', 'Chad'),
    ('CL', 'تشيلي', 'Chile'),
    ('CN', 'الصين', 'China'),
    ('CX', 'جزيرة كريسماس', 'Christmas Island'),
    ('CC', 'جزر كوكوس (كيلينغ)', 'Cocos (Keeling) Islands'),
    ('CO', 'كولومبيا', 'Colombia'),
    ('KM', 'جزر القمر', 'Comoros'),
    ('CG', 'الكونغو', 'Congo'),
    ('CK', 'جزر كوك', 'Cook Islands'),
    ('CR', 'كوستاريكا', 'Costa Rica'),
    ('HR', 'كرواتيا', 'Croatia'),
    ('CU', 'كوبا', 'Cuba'),
    ('CW', 'كوراساو', 'Curaçao'),
    ('CY', 'قبرص', 'Cyprus'),
    ('CZ', 'التشيك', 'Czechia'),
    ('CI', 'ساحل العاج', 'Côte d’Ivoire'),
    ('CD', 'الكونغو الديمقراطية', 'DR Congo'),
    ('DK', 'الدانمرك', 'Denmark'),
    ('DJ', 'جيبوتي', 'Djibouti'),
    ('DM', 'دومينيكا', 'Dominica'),
    ('DO', 'جمهورية الدومينيكان', 'Dominican Republic'),
    ('EC', 'الإكوادور', 'Ecuador'),
    ('EG', 'مصر', 'Egypt'),
    ('SV', 'السلفادور', 'El Salvador'),
    ('GQ', 'غينيا الاستوائية', 'Equatorial Guinea'),
    ('ER', 'إريتريا', 'Eritrea'),
    ('EE', 'إستونيا', 'Estonia'),
    ('SZ', 'إسواتيني', 'Eswatini'),
    ('ET', 'إثيوبيا', 'Ethiopia'),
    ('FK', 'جزر فوكلاند', 'Falkland Islands'),
    ('FO', 'جزر فارو', 'Faroe Islands'),
    ('FJ', 'فيجي', 'Fiji'),
    ('FI', 'فنلندا', 'Finland'),
    ('FR', 'فرنسا', 'France'),
    ('GF', 'غويانا الفرنسية', 'French Guiana'),
    ('PF', 'بولينيزيا الفرنسية', 'French Polynesia'),
    ('GA', 'الغابون', 'Gabon'),
    ('GM', 'غامبيا', 'Gambia'),
    ('GE', 'جورجيا', 'Georgia'),
    ('DE', 'ألمانيا', 'Germany'),
    ('GH', 'غانا', 'Ghana'),
    ('GI', 'جبل طارق', 'Gibraltar'),
    ('GR', 'اليونان', 'Greece'),
    ('GL', 'غرينلاند', 'Greenland'),
    ('GD', 'غرينادا', 'Grenada'),
    ('GP', 'غوادلوب', 'Guadeloupe'),
    ('GU', 'غوام', 'Guam'),
    ('GT', 'غواتيمالا', 'Guatemala'),
    ('GG', 'غيرنزي', 'Guernsey'),
    ('GN', 'غينيا', 'Guinea'),
    ('GW', 'غينيا بيساو', 'Guinea-Bissau'),
    ('GY', 'غيانا', 'Guyana'),
    ('HT', 'هايتي', 'Haiti'),
    ('HN', 'هندوراس', 'Honduras'),
    ('HK', 'هونغ كونغ', 'Hong Kong'),
    ('HU', 'هنغاريا', 'Hungary'),
    ('IS', 'آيسلندا', 'Iceland'),
    ('IN', 'الهند', 'India'),
    ('ID', 'إندونيسيا', 'Indonesia'),
    ('IR', 'إيران', 'Iran'),
    ('IQ', 'العراق', 'Iraq'),
    ('IE', 'أيرلندا', 'Ireland'),
    ('IM', 'جزيرة مان', 'Isle of Man'),
    ('IL', 'إسرائيل', 'Israel'),
    ('IT', 'إيطاليا', 'Italy'),
    ('JM', 'جامايكا', 'Jamaica'),
    ('JP', 'اليابان', 'Japan'),
    ('JE', 'جيرسي', 'Jersey'),
    ('JO', 'الأردن', 'Jordan'),
    ('KZ', 'كازاخستان', 'Kazakhstan'),
    ('KE', 'كينيا', 'Kenya'),
    ('KI', 'كيريباتي', 'Kiribati'),
    ('KW', 'الكويت', 'Kuwait'),
    ('KG', 'قيرغيزستان', 'Kyrgyzstan'),
    ('LA', 'لاوس', 'Laos'),
    ('LV', 'لاتفيا', 'Latvia'),
    ('LB', 'لبنان', 'Lebanon'),
    ('LS', 'ليسوتو', 'Lesotho'),
    ('LR', 'ليبيريا', 'Liberia'),
    ('LY', 'ليبيا', 'Libya'),
    ('LI', 'ليختنشتاين', 'Liechtenstein'),
    ('LT', 'ليتوانيا', 'Lithuania'),
    ('LU', 'لوكسمبورغ', 'Luxembourg'),
    ('MO', 'ماكاو', 'Macao'),
    ('MG', 'مدغشقر', 'Madagascar'),
    ('MW', 'ملاوي', 'Malawi'),
    ('MY', 'ماليزيا', 'Malaysia'),
    ('MV', 'جزر المالديف', 'Maldives'),
    ('ML', 'مالي', 'Mali'),
    ('MT', 'مالطا', 'Malta'),
    ('MH', 'جزر مارشال', 'Marshall Islands'),
    ('MQ', 'جزر المارتينيك', 'Martinique'),
    ('MR', 'موريتانيا', 'Mauritania'),
    ('MU', 'موريشيوس', 'Mauritius'),
    ('YT', 'مايوت', 'Mayotte'),
    ('MX', 'المكسيك', 'Mexico'),
    ('FM', 'ميكرونيزيا', 'Micronesia'),
    ('MD', 'مولدوفا', 'Moldova'),
    ('MC', 'موناكو', 'Monaco'),
    ('MN', 'منغوليا', 'Mongolia'),
    ('ME', 'الجبل الأسود', 'Montenegro'),
    ('MS', 'مونتسرات', 'Montserrat'),
    ('MA', 'المغرب', 'Morocco'),
    ('MZ', 'موزمبيق', 'Mozambique'),
    ('MM', 'ميانمار', 'Myanmar'),
    ('NA', 'ناميبيا', 'Namibia'),
    ('NR', 'ناورو', 'Nauru'),
    ('NP', 'نيبال', 'Nepal'),
    ('NL', 'هولندا', 'Netherlands'),
    ('NC', 'كاليدونيا الجديدة', 'New Caledonia'),
    ('NZ', 'نيوزيلندا', 'New Zealand'),
    ('NI', 'نيكاراغوا', 'Nicaragua'),
    ('NE', 'النيجر', 'Niger'),
    ('NG', 'نيجيريا', 'Nigeria'),
    ('NU', 'نيوي', 'Niue'),
    ('NF', 'جزيرة نورفولك', 'Norfolk Island'),
    ('KP', 'كوريا الشمالية', 'North Korea'),
    ('MK', 'مقدونيا الشمالية', 'North Macedonia'),
    ('MP', 'جزر ماريانا الشمالية', 'Northern Mariana Islands'),
    ('NO', 'النرويج', 'Norway'),
    ('OM', 'عُمان', 'Oman'),
    ('PK', 'باكستان', 'Pakistan'),
    ('PW', 'بالاو', 'Palau'),
    ('PS', 'فلسطين', 'Palestine'),
    ('PA', 'بنما', 'Panama'),
    ('PG', 'بابوا غينيا الجديدة', 'Papua New Guinea'),
    ('PY', 'باراغواي', 'Paraguay'),
    ('PE', 'بيرو', 'Peru'),
    ('PH', 'الفلبين', 'Philippines'),
    ('PN', 'جزر بيتكيرن', 'Pitcairn Islands'),
    ('PL', 'بولندا', 'Poland'),
    ('PT', 'البرتغال', 'Portugal'),
    ('PR', 'بورتوريكو', 'Puerto Rico'),
    ('QA', 'قطر', 'Qatar'),
    ('RO', 'رومانيا', 'Romania'),
    ('RU', 'روسيا', 'Russia'),
    ('RW', 'رواندا', 'Rwanda'),
    ('RE', 'روينيون', 'Réunion'),
    ('WS', 'ساموا', 'Samoa'),
    ('SM', 'سان مارينو', 'San Marino'),
    ('SA', 'السعودية', 'Saudi Arabia'),
    ('SN', 'السنغال', 'Senegal'),
    ('RS', 'صربيا', 'Serbia'),
    ('SC', 'سيشل', 'Seychelles'),
    ('SL', 'سيراليون', 'Sierra Leone'),
    ('SG', 'سنغافورة', 'Singapore'),
    ('SX', 'سانت مارتن', 'Sint Maarten'),
    ('SK', 'سلوفاكيا', 'Slovakia'),
    ('SI', 'سلوفينيا', 'Slovenia'),
    ('SB', 'جزر سليمان', 'Solomon Islands'),
    ('SO', 'الصومال', 'Somalia'),
    ('ZA', 'جنوب أفريقيا', 'South Africa'),
    ('KR', 'كوريا الجنوبية', 'South Korea'),
    ('SS', 'جنوب السودان', 'South Sudan'),
    ('ES', 'إسبانيا', 'Spain'),
    ('LK', 'سريلانكا', 'Sri Lanka'),
    ('BL', 'سان بارتليمي', 'St. Barthélemy'),
    ('SH', 'سانت هيلينا', 'St. Helena'),
    ('KN', 'سانت كيتس ونيفيس', 'St. Kitts & Nevis'),
    ('LC', 'سانت لوسيا', 'St. Lucia'),
    ('MF', 'سان مارتن', 'St. Martin'),
    ('PM', 'سان بيير ومكويلون', 'St. Pierre & Miquelon'),
    ('VC', 'سانت فنسنت وجزر غرينادين', 'St. Vincent & the Grenadines'),
    ('SD', 'السودان', 'Sudan'),
    ('SR', 'سورينام', 'Suriname'),
    ('SJ', 'سفالبارد وجان ماين', 'Svalbard & Jan Mayen'),
    ('SE', 'السويد', 'Sweden'),
    ('CH', 'سويسرا', 'Switzerland'),
    ('SY', 'سوريا', 'Syria'),
    ('ST', 'ساو تومي وبرينسيبي', 'São Tomé & Príncipe'),
    ('TW', 'تايوان', 'Taiwan'),
    ('TJ', 'طاجيكستان', 'Tajikistan'),
    ('TZ', 'تنزانيا', 'Tanzania'),
    ('TH', 'تايلاند', 'Thailand'),
    ('TL', 'تيمور الشرقية', 'Timor-Leste'),
    ('TG', 'توغو', 'Togo'),
    ('TK', 'توكيلاو', 'Tokelau'),
    ('TO', 'تونغا', 'Tonga'),
    ('TT', 'ترينيداد وتوباغو', 'Trinidad & Tobago'),
    ('TN', 'تونس', 'Tunisia'),
    ('TM', 'تركمانستان', 'Turkmenistan'),
    ('TC', 'جزر توركس وكايكوس', 'Turks & Caicos Islands'),
    ('TV', 'توفالو', 'Tuvalu'),
    ('TR', 'تركيا', 'Türkiye'),
    ('VI', 'جزر فيرجن الأمريكية', 'U.S. Virgin Islands'),
    ('UG', 'أوغندا', 'Uganda'),
    ('UA', 'أوكرانيا', 'Ukraine'),
    ('AE', 'الإمارات', 'United Arab Emirates'),
    ('GB', 'المملكة المتحدة', 'United Kingdom'),
    ('US', 'الولايات المتحدة الأمريكية', 'United States'),
    ('UY', 'أورغواي', 'Uruguay'),
    ('UZ', 'أوزبكستان', 'Uzbekistan'),
    ('VU', 'فانواتو', 'Vanuatu'),
    ('VA', 'الفاتيكان', 'Vatican City'),
    ('VE', 'فنزويلا', 'Venezuela'),
    ('VN', 'فيتنام', 'Vietnam'),
    ('WF', 'جزر والس وفوتونا', 'Wallis & Futuna'),
    ('EH', 'الصحراء الغربية', 'Western Sahara'),
    ('YE', 'اليمن', 'Yemen'),
    ('ZM', 'زامبيا', 'Zambia'),
    ('ZW', 'زيمبابوي', 'Zimbabwe'),
    ('AX', 'جزر آلاند', 'Åland Islands'),
]
