# Generated by Django 6.1.1 on 2026-09-11 06:56

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_ar', models.CharField(max_length=255)),
                ('text_en', models.CharField(blank=True, default='', max_length=255)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['ordering', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title_ar', models.CharField(blank=True, default='', max_length=160)),
                ('title_en', models.CharField(blank=True, default='', max_length=160)),
                ('subtitle_ar', models.CharField(blank=True, default='', max_length=255)),
                ('subtitle_en', models.CharField(blank=True, default='', max_length=255)),
                ('button_text_ar', models.CharField(blank=True, default='', max_length=60)),
                ('button_text_en', models.CharField(blank=True, default='', max_length=60)),
                ('link', models.CharField(blank=True, default='', max_length=255)),
                ('image', models.ImageField(upload_to='banners/')),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=120)),
                ('name_en', models.CharField(blank=True, default='', max_length=120)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=160, unique=True)),
                ('description_ar', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/')),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Categories',
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('subject', models.CharField(blank=True, default='', max_length=160)),
                ('message', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Governorate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=80)),
                ('name_en', models.CharField(blank=True, default='', max_length=80)),
                ('shipping_fee', models.DecimalField(blank=True, decimal_places=2, help_text='اتركه فارغًا لاستخدام سعر الشحن العام / blank = default fee', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering', 'name_ar'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name_ar', models.CharField(default='RGS TOWER', max_length=120)),
                ('brand_name_en', models.CharField(default='RGS TOWER', max_length=120)),
                ('tagline_ar', models.CharField(blank=True, default='أناقة الرجل الحقيقي', max_length=200)),
                ('tagline_en', models.CharField(blank=True, default='Menswear, refined.', max_length=200)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('about_ar', models.TextField(blank=True, default='')),
                ('about_en', models.TextField(blank=True, default='')),
                ('phone', models.CharField(blank=True, default='', max_length=40)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=40)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address_ar', models.CharField(blank=True, default='', max_length=255)),
                ('address_en', models.CharField(blank=True, default='', max_length=255)),
                ('facebook_url', models.URLField(blank=True, default='')),
                ('instagram_url', models.URLField(blank=True, default='')),
                ('tiktok_url', models.URLField(blank=True, default='')),
                ('youtube_url', models.URLField(blank=True, default='')),
                ('currency_ar', models.CharField(default='ج.م', max_length=20)),
                ('currency_en', models.CharField(default='EGP', max_length=20)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=10)),
                ('free_shipping_threshold', models.DecimalField(decimal_places=2, default=Decimal('2000.00'), help_text='0 = لا يوجد شحن مجاني / 0 disables free shipping', max_digits=10)),
                ('low_stock_threshold', models.PositiveIntegerField(default=5)),
                ('orders_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Site settings',
                'verbose_name_plural': 'Site settings',
            },
        ),
        migrations.CreateModel(
            name='Size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, unique=True)),
                ('name_ar', models.CharField(blank=True, default='', max_length=20)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=40, unique=True)),
                ('description', models.CharField(blank=True, default='', max_length=200)),
                ('discount_type', models.CharField(choices=[('percent', 'نسبة مئوية / Percent'), ('fixed', 'مبلغ ثابت / Fixed amount')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('min_order', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('free_shipping', models.BooleanField(default=False)),
                ('max_uses', models.PositiveIntegerField(default=0, help_text='0 = غير محدود / 0 = unlimited')),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='coupons', to='dashboard.category')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(blank=True, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('phone', models.CharField(max_length=30)),
                ('phone_alt', models.CharField(blank=True, default='', max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('city', models.CharField(blank=True, default='', max_length=120)),
                ('address', models.TextField()),
                ('notes', models.TextField(blank=True, default='')),
                ('subtotal', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('discount_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('coupon_code', models.CharField(blank=True, default='', max_length=40)),
                ('shipping_fee', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'قيد المراجعة / Pending'), ('confirmed', 'تم التأكيد / Confirmed'), ('shipped', 'تم الشحن / Shipped'), ('delivered', 'تم التسليم / Delivered'), ('cancelled', 'ملغي / Cancelled')], default='pending', max_length=12)),
                ('admin_note', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('coupon', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dashboard.coupon')),
                ('governorate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='dashboard.governorate')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=200)),
                ('name_en', models.CharField(blank=True, default='', max_length=200)),
                ('slug', models.SlugField(allow_unicode=True, blank=True, max_length=240, unique=True)),
                ('sku', models.CharField(blank=True, default='', max_length=60)),
                ('short_ar', models.CharField(blank=True, default='', max_length=255)),
                ('short_en', models.CharField(blank=True, default='', max_length=255)),
                ('description_ar', models.TextField(blank=True, default='')),
                ('description_en', models.TextField(blank=True, default='')),
                ('price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('compare_price', models.DecimalField(blank=True, decimal_places=2, help_text='السعر قبل الخصم (اختياري) / original price, optional', max_digits=10, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_new', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='dashboard.category')),
            ],
            options={
                'ordering': ['ordering', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProductColor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_ar', models.CharField(max_length=60)),
                ('name_en', models.CharField(blank=True, default='', max_length=60)),
                ('hex_code', models.CharField(default='#000000', max_length=9)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='colors', to='dashboard.product')),
            ],
            options={
                'ordering': ['ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/')),
                ('is_main', models.BooleanField(default=False)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='dashboard.product')),
            ],
            options={
                'ordering': ['-is_main', 'ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ProductVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=0)),
                ('sku', models.CharField(blank=True, default='', max_length=60)),
                ('color', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='dashboard.productcolor')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='dashboard.product')),
                ('size', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='dashboard.size')),
            ],
            options={
                'ordering': ['color__ordering', 'size__ordering', 'id'],
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('color_name', models.CharField(blank=True, default='', max_length=60)),
                ('size_name', models.CharField(blank=True, default='', max_length=40)),
                ('image_url', models.CharField(blank=True, default='', max_length=300)),
                ('unit_price', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('line_total', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='dashboard.order')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='dashboard.product')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='dashboard.productvariant')),
            ],
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('scope', models.CharField(choices=[('all', 'كل المنتجات / All products'), ('category', 'كاتيجوري معينة / Selected categories'), ('product', 'منتجات معينة / Selected products')], default='all', max_length=12)),
                ('discount_type', models.CharField(choices=[('percent', 'نسبة مئوية / Percent'), ('fixed', 'مبلغ ثابت / Fixed amount')], default='percent', max_length=10)),
                ('value', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('badge_ar', models.CharField(blank=True, default='', max_length=40)),
                ('badge_en', models.CharField(blank=True, default='', max_length=40)),
                ('start_at', models.DateTimeField(blank=True, null=True)),
                ('end_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('categories', models.ManyToManyField(blank=True, related_name='promotions', to='dashboard.category')),
                ('products', models.ManyToManyField(blank=True, related_name='promotions', to='dashboard.product')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddConstraint(
            model_name='productvariant',
            constraint=models.UniqueConstraint(fields=('product', 'color', 'size'), name='uniq_product_color_size'),
        ),
    ]
