# Generated by Django 6.1.2 on 2026-09-20 06:54

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="HomeSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "key",
                    models.CharField(
                        choices=[
                            ("hero", "الواجهة الرئيسية (Hero)"),
                            ("banners", "سلايدر البانرات"),
                            ("features", "مميزات المتجر"),
                            ("categories", "الأقسام"),
                            ("featured", "منتجات مختارة"),
                            ("about", "من نحن"),
                            ("portfolio", "أعمالنا"),
                            ("sale", "العروض"),
                            ("new_arrivals", "وصل حديثًا"),
                            ("reviews", "تقييمات العملاء"),
                        ],
                        max_length=30,
                        unique=True,
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("eyebrow_ar", models.CharField(blank=True, default="", max_length=80)),
                ("eyebrow_en", models.CharField(blank=True, default="", max_length=80)),
                (
                    "title_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="في الـ Hero: السطر التاني بعد Enter بيتلوّن",
                        max_length=200,
                    ),
                ),
                ("title_en", models.CharField(blank=True, default="", max_length=200)),
                ("subtitle_ar", models.TextField(blank=True, default="")),
                ("subtitle_en", models.TextField(blank=True, default="")),
                (
                    "button_text_ar",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "button_text_en",
                    models.CharField(blank=True, default="", max_length=60),
                ),
                (
                    "button_link",
                    models.CharField(blank=True, default="", max_length=255),
                ),
                ("image", models.ImageField(blank=True, null=True, upload_to="home/")),
                ("items_limit", models.PositiveSmallIntegerField(default=8)),
            ],
            options={
                "ordering": ["ordering", "id"],
            },
        ),
        migrations.CreateModel(
            name="Policy",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_ar", models.CharField(max_length=160)),
                ("title_en", models.CharField(blank=True, default="", max_length=160)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=190, unique=True
                    ),
                ),
                ("content_ar", models.TextField(blank=True, default="")),
                ("content_en", models.TextField(blank=True, default="")),
                ("is_active", models.BooleanField(default=True)),
                ("show_in_footer", models.BooleanField(default=True)),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name_plural": "Policies",
                "ordering": ["ordering", "id"],
            },
        ),
        migrations.CreateModel(
            name="WorkCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name_ar", models.CharField(max_length=80)),
                ("name_en", models.CharField(blank=True, default="", max_length=80)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=100, unique=True
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
            ],
            options={
                "verbose_name_plural": "Work categories",
                "ordering": ["ordering", "id"],
            },
        ),
        migrations.AddField(
            model_name="order",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="order",
            name="pay_amount",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="المبلغ بعملة PayPal (دولار)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="pay_currency",
            field=models.CharField(blank=True, default="", max_length=3),
        ),
        migrations.AddField(
            model_name="order",
            name="payer_email",
            field=models.CharField(blank=True, default="", max_length=254),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("paypal", "PayPal"), ("cod", "الدفع عند الاستلام")],
                default="cod",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_reference",
            field=models.CharField(
                blank=True,
                default="",
                help_text="رقم العملية اللي كتبه العميل بعد الدفع باللينك",
                max_length=120,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("unpaid", "لم يتم الدفع"),
                    ("pending", "بانتظار تأكيد الدفع"),
                    ("paid", "مدفوع"),
                    ("failed", "فشل الدفع"),
                    ("refunded", "مسترد"),
                ],
                default="unpaid",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="paypal_capture_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="paypal_order_id",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="order",
            name="stock_restored",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="cod_enabled",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="paypal_client_id",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="paypal_currency",
            field=models.CharField(default="USD", max_length=3),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="paypal_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="paypal_link",
            field=models.URLField(
                blank=True,
                default="",
                help_text="لينك الدفع — مثال: https://paypal.me/YourName",
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="paypal_rate",
            field=models.DecimalField(
                decimal_places=4,
                default=Decimal("50.0000"),
                help_text="كام جنيه = 1 دولار",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="paypal_sandbox",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="paypal_secret",
            field=models.CharField(blank=True, default="", max_length=255),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="reviews_auto_publish",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="share_image",
            field=models.ImageField(blank=True, null=True, upload_to="site/"),
        ),
        migrations.CreateModel(
            name="CustomerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(blank=True, default="", max_length=30)),
                ("phone_alt", models.CharField(blank=True, default="", max_length=30)),
                ("city", models.CharField(blank=True, default="", max_length=120)),
                ("address", models.TextField(blank=True, default="")),
                ("admin_note", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "governorate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="customers",
                        to="dashboard.governorate",
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="customer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="NavLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "link_type",
                    models.CharField(
                        choices=[
                            ("home", "الرئيسية"),
                            ("shop", "المتجر"),
                            ("new", "وصل حديثًا"),
                            ("sale", "العروض"),
                            ("portfolio", "أعمالنا"),
                            ("reviews", "تقييمات العملاء"),
                            ("about", "من نحن"),
                            ("contact", "اتصل بنا"),
                            ("track", "تتبع الطلب"),
                            ("category", "قسم من المتجر"),
                            ("policy", "صفحة سياسة"),
                            ("custom", "رابط مخصص"),
                        ],
                        default="custom",
                        max_length=12,
                    ),
                ),
                (
                    "label_ar",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="اتركه فاضي للاسم الافتراضي",
                        max_length=60,
                    ),
                ),
                ("label_en", models.CharField(blank=True, default="", max_length=60)),
                (
                    "url",
                    models.CharField(
                        blank=True,
                        default="",
                        help_text="للرابط المخصص فقط",
                        max_length=255,
                    ),
                ),
                ("new_tab", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("ordering", models.PositiveIntegerField(default=0)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nav_links",
                        to="dashboard.category",
                    ),
                ),
                (
                    "policy",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nav_links",
                        to="dashboard.policy",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "id"],
            },
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                (
                    "rating",
                    models.PositiveSmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("comment", models.TextField()),
                (
                    "reply",
                    models.TextField(
                        blank=True,
                        default="",
                        help_text="رد المتجر (بيظهر تحت التقييم)",
                    ),
                ),
                ("is_approved", models.BooleanField(default=False)),
                ("is_featured", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "order",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="review",
                        to="dashboard.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="StaffProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("job_title", models.CharField(blank=True, default="", max_length=80)),
                ("permissions", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="staff_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Work",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title_ar", models.CharField(max_length=160)),
                ("title_en", models.CharField(blank=True, default="", max_length=160)),
                (
                    "slug",
                    models.SlugField(
                        allow_unicode=True, blank=True, max_length=190, unique=True
                    ),
                ),
                (
                    "summary_ar",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                (
                    "summary_en",
                    models.CharField(blank=True, default="", max_length=300),
                ),
                ("description_ar", models.TextField(blank=True, default="")),
                ("description_en", models.TextField(blank=True, default="")),
                (
                    "cover",
                    models.ImageField(
                        help_text="البانر — بيظهر فوق صفحة العمل وتحت الرابط لما تبعته لحد",
                        upload_to="works/covers/",
                    ),
                ),
                ("client", models.CharField(blank=True, default="", max_length=120)),
                ("work_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "is_featured",
                    models.BooleanField(
                        default=False, help_text="يظهر في الصفحة الرئيسية"
                    ),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("views", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="works",
                        to="dashboard.workcategory",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="WorkMedia",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "صورة"),
                            ("video", "فيديو مرفوع"),
                            ("embed", "فيديو يوتيوب / فيميو"),
                        ],
                        default="image",
                        max_length=10,
                    ),
                ),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="works/media/"),
                ),
                (
                    "video",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="works/videos/",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["mp4", "webm", "mov", "m4v"]
                            )
                        ],
                    ),
                ),
                (
                    "poster",
                    models.ImageField(
                        blank=True,
                        help_text="صورة غلاف للفيديو (اختياري)",
                        null=True,
                        upload_to="works/posters/",
                    ),
                ),
                ("embed_url", models.URLField(blank=True, default="")),
                (
                    "caption_ar",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                (
                    "caption_en",
                    models.CharField(blank=True, default="", max_length=200),
                ),
                ("ordering", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "work",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="media",
                        to="dashboard.work",
                    ),
                ),
            ],
            options={
                "ordering": ["ordering", "id"],
            },
        ),
    ]
