# Generated by Django 6.1.2.dev20260918142906 on 2026-09-20 15:43

import dashboard.models
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0004_countries"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sitesettings",
            name="emails_enabled",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_customer_order",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_customer_ticket",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_email",
            field=models.EmailField(
                blank=True,
                default="",
                help_text="الإيميل اللي هتوصلك عليه الإشعارات",
                max_length=254,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_new_message",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_new_order",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_new_review",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="notify_new_ticket",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="site_url",
            field=models.CharField(
                blank=True,
                default="",
                help_text="لينك المتجر — بيتحط في الإيميلات، مثال: https://rgstower.com",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_host",
            field=models.CharField(
                blank=True, default="smtp.gmail.com", max_length=120
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_password",
            field=models.CharField(
                blank=True,
                default="",
                help_text="App password من جوجل (16 حرف) — مش باسورد الإيميل العادي",
                max_length=200,
            ),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_port",
            field=models.PositiveIntegerField(default=587),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_use_tls",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sitesettings",
            name="smtp_user",
            field=models.CharField(
                blank=True,
                default="",
                help_text="الجيميل اللي هيبعت منه",
                max_length=200,
            ),
        ),
        migrations.CreateModel(
            name="Ticket",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.CharField(blank=True, max_length=20, unique=True)),
                ("subject", models.CharField(max_length=160)),
                (
                    "topic",
                    models.CharField(
                        choices=[
                            ("order", "استفسار عن طلب"),
                            ("product", "سؤال عن منتج"),
                            ("shipping", "الشحن والتوصيل"),
                            ("payment", "الدفع"),
                            ("return", "استبدال أو استرجاع"),
                            ("other", "موضوع آخر"),
                        ],
                        default="other",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "مفتوحة"),
                            ("answered", "تم الرد"),
                            ("closed", "مقفولة"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("admin_unread", models.BooleanField(default=True)),
                ("user_unread", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "last_message_at",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tickets",
                        to="dashboard.order",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="tickets",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-last_message_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_staff", models.BooleanField(default=False)),
                ("body", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "author",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="ticket_messages",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "ticket",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="messages",
                        to="dashboard.ticket",
                    ),
                ),
            ],
            options={
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="TicketAttachment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        upload_to=dashboard.models.ticket_upload_to,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                [
                                    "jpg",
                                    "jpeg",
                                    "png",
                                    "webp",
                                    "gif",
                                    "heic",
                                    "webm",
                                    "mp3",
                                    "m4a",
                                    "ogg",
                                    "oga",
                                    "wav",
                                    "aac",
                                    "mp4a",
                                    "pdf",
                                    "doc",
                                    "docx",
                                    "txt",
                                    "xlsx",
                                    "csv",
                                    "zip",
                                    "mp4",
                                    "mov",
                                ]
                            )
                        ],
                    ),
                ),
                ("name", models.CharField(blank=True, default="", max_length=200)),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("image", "صورة"),
                            ("audio", "تسجيل صوتي"),
                            ("file", "ملف"),
                        ],
                        default="file",
                        max_length=10,
                    ),
                ),
                ("size", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attachments",
                        to="dashboard.ticketmessage",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
