# Generated by Django 6.1.2.dev20260918142906 on 2026-09-20 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dashboard", "0005_tickets_and_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="navlink",
            name="link_type",
            field=models.CharField(
                choices=[
                    ("home", "الرئيسية"),
                    ("shop", "المتجر"),
                    ("new", "وصل حديثًا"),
                    ("sale", "العروض"),
                    ("portfolio", "أعمالنا"),
                    ("reviews", "تقييمات العملاء"),
                    ("about", "من نحن"),
                    ("contact", "اتصل بنا"),
                    ("track", "تتبع الطلب"),
                    ("support", "الدعم والتذاكر"),
                    ("category", "قسم من المتجر"),
                    ("policy", "صفحة سياسة"),
                    ("custom", "رابط مخصص"),
                ],
                default="custom",
                max_length=12,
            ),
        ),
    ]
